---
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 52b230c ( new yaml file)
- name: Setup Java and Users
  hosts: all
  become: true
  vars:
    java_package: openjdk-17-jdk
    users:
      - name: alice
        password: "password123"
      - name: bob
        password: "password123"
  tasks:

<<<<<<< HEAD
=======
=======
- name: Install Java, Create Users, Set Env Variables
  hosts: all
  become: true

  vars:
    java_package: openjdk-11-jdk
    users:
      - name: user1
        password: "{{ 'password123' | password_hash('sha512') }}"
      - name: user2
        password: "{{ 'defaultpass' | password_hash('sha512') }}"
    java_home: "/usr/lib/jvm/java-11-openjdk-amd64"

  tasks:
>>>>>>> 25a78a6 (ansible tasks)
>>>>>>> 52b230c ( new yaml file)
    - name: Install Java JDK
      apt:
        name: "{{ java_package }}"
        state: present
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 52b230c ( new yaml file)
        update_cache: yes

    - name: Create users with default passwords
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Set JAVA_HOME in /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        create: yes

    - name: Export JAVA_HOME to all users
      lineinfile:
        path: /etc/profile.d/java.sh
        line: 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        create: yes
        mode: '0755'
<<<<<<< HEAD
=======
=======
        update_cache: true

    - name: Create local user accounts
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Set JAVA_HOME environment variable
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME={{ java_home }}
          export PATH=$JAVA_HOME/bin:$PATH
        mode: '0644'
>>>>>>> 25a78a6 (ansible tasks)
>>>>>>> 52b230c ( new yaml file)

