---
- name: Setup Nginx as a Reverse Proxy
  hosts: all
  become: yes

  vars:
    app_port: 3000              # Backend app (Node.js, etc.)
    nginx_port: 8081            # New Nginx reverse proxy port
    nginx_proxy_file: /etc/nginx/sites-available/reverse-proxy
    nginx_proxy_link: /etc/nginx/sites-enabled/reverse-proxy

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create Nginx reverse proxy config on port {{ nginx_port }}
      copy:
        dest: "{{ nginx_proxy_file }}"
        content: |
          server {
              listen {{ nginx_port }};
              server_name _;

              location / {
                  proxy_pass http://localhost:{{ app_port }};
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable the reverse proxy configuration
      file:
        src: "{{ nginx_proxy_file }}"
        dest: "{{ nginx_proxy_link }}"
        state: link
        force: yes

    - name: Remove default Nginx config if it exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    - name: Show Nginx test output
      debug:
        var: nginx_test.stderr_lines

    - name: Restart and enable Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

