---
- name: Create and manage S3 buckets
  hosts: all
  connection: local
  gather_facts: false

  vars:
    bucket_name: my-ansible-test-bucket-sandeep1
    bucket_region: us-east-2

  tasks:
    - name: Create S3 bucket safely
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ bucket_region }}"
      register: create_bucket_result
      retries: 5
      delay: 10
      until: create_bucket_result is succeeded

    - name: Enable versioning on the bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        versioning: true
        region: "{{ bucket_region }}"

    - name: Tag the S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        tags:
          Environment: Dev
          Owner: Ansible
        region: "{{ bucket_region }}"

